logging:
    file:
        name: /logs/lotteOn.log

    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
        org.springframework.web: DEBUG
server:
    port: 8085
    servlet:
        context-path: /

spring:
    application:
        name: LotteOnProject-3조
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        password: Qwe123~!
        url: jdbc:mysql://43.202.32.28:3306/lotteProject
        username: lotte
        hikari:
            minimum-idle: 5          # 최소 유휴 커넥션 수 설정
            maximum-pool-size: 30    # 최대 커넥션 수를 늘려봄 (20 이상 필요 시)
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            validation-timeout: 5000
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    devtools:
        livereload:
            enabled: true
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    web:
        resources:
            static-locations:
                - classpath:/static/
                - file:uploads/
    thymeleaf:
        cache: false
        check-template-location: true
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
    cache:
        type: redis
        redis:
            time-to-live: 86400s

    data:
        redis:
            host: 43.202.32.28
            port: 6379
            repositories:
                enabled: true
            lettuce:
                pool:
                    max-wait: 5000ms

    security:
        remember-me:
            key: "1234Asd@"
        oauth2:
            client:
                registration:
                    google:
                        client-id: 260686576423-cd9o4qepuuq5mfnprhbftso2h3h8nqv5.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://ec2-43-202-32-28.ap-northeast-2.compute.amazonaws.com:8085/login/oauth2/code/google
                        scope:
                            - email
                            - profile

                    kakao:
                        client-id: e854d74518514c68abdc06c8cd750f0f
                        client-secret: 0PlxjR5lcZSTbH5aXvrJhaT53s91vaBI
                        scope:
                            - profile_nickname
                            - account_email
                        redirect-uri: http://ec2-43-202-32-28.ap-northeast-2.compute.amazonaws.com:8085/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-name: Kakao

                    naver:
                        client-id: hnfj6EGOh8O38QYjYbjI
                        client-secret: dhMEtyQF55
                        scope:
                            - name
                            - email
                        redirect-uri: http://ec2-43-202-32-28.ap-northeast-2.compute.amazonaws.com:8085/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: Naver

                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: name

                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response


management:
    endpoint:
        caches:
            enabled: true
        metrics:
            enabled: true


